# Basic Python

## 1. Split this string

In [1]:
v = "Hi i am Vignesh!"

In [2]:
print(v.split(" "))

['Hi', 'i', 'am', 'Vignesh!']


## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [4]:
planet = "Earth"
diameter = 12742

In [5]:
print("The diameter of {0} is {1} kilometers.".format(planet,diameter))

The diameter of Earth is 12742 kilometers.


## 3. In this nest dictionary grab the word "hello"

In [6]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [9]:
print(d["k1"][3]["tricky"][3]["target"][3])

hello


# Numpy

In [11]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [12]:
print(np.zeros(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [13]:
print(np.ones(10)*5)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


## 5. Create an array of all the even integers from 20 to 35

In [14]:
print(np.arange(20,35,2))

[20 22 24 26 28 30 32 34]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [18]:
print(np.arange(0,9).reshape(3,3))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [25]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(np.concatenate((a,b),axis=0))

[1 2 3 4 5 6]


# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [1]:
import pandas as pd

In [2]:
data=[["Harish","leader"],["Pavithran","Member"],["Akash","Member"],["Vignesh","Member"]]
print(pd.DataFrame(data,columns=["Name","Roll"]))

        Name    Roll
0     Harish  leader
1  Pavithran  Member
2      Akash  Member
3    Vignesh  Member


## 9. Generate the series of dates from 1st Jan, 2023 to 15th Mar, 2023

In [3]:
from datetime import datetime

date=pd.date_range(start="2023-01-01",end="2023-03-15")
print(pd.Series(date))

0    2023-01-01
1    2023-01-02
2    2023-01-03
3    2023-01-04
4    2023-01-05
        ...    
69   2023-03-11
70   2023-03-12
71   2023-03-13
72   2023-03-14
73   2023-03-15
Length: 74, dtype: datetime64[ns]


## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [33]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [37]:
pd.DataFrame(lists,columns=["No.""Name","ID"])

No. Name  ID
0    1  aaa  22
1    2  bbb  25
2    3  ccc  24